"use client"

import { LockKeyhole, Send } from "lucide-react"
import { useState } from "react"
import { apiFetch } from "@/lib/api"

export function ContributionConsole() {
  const [title, setTitle] = useState("")
  const [body, setBody] = useState("")
  const [evidenceAttached, setEvidenceAttached] = useState(false)
  const [submitted, setSubmitted] = useState<string | null>(null)
  const [error, setError] = useState<string | null>(null)
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(null); try { const response = await apiFetch<{ data: { id: string } }>("/api/v1/submissions", { method: "POST", body: JSON.stringify({ title, body, evidenceAttached }) }); setSubmitted(response.data.id) } catch { setError("Submission could not be sent. Check the API service and required fields.") } }
  return <div className="grid gap-px border border-border bg-border lg:grid-cols-12"><form onSubmit={submit} className="space-y-5 bg-background p-6 md:p-8 lg:col-span-7"><div className="flex items-center gap-3 border-b border-border pb-5"><LockKeyhole className="h-5 w-5 text-accent" /><div><p className="font-mono text-[10px] uppercase tracking-widest text-muted-foreground">Contributor intake</p><p className="text-sm font-semibold">Submit without identity fields</p></div></div><label className="block"><span className="font-mono text-[10px] uppercase tracking-widest text-muted-foreground">Contribution title</span><input required value={title} onChange={(event) => setTitle(event.target.value)} className="mt-2 block w-full border border-border bg-secondary px-3 py-3 text-sm outline-none focus:border-accent" /></label><label className="block"><span className="font-mono text-[10px] uppercase tracking-widest text-muted-foreground">Contribution</span><textarea required minLength={10} value={body} onChange={(event) => setBody(event.target.value)} rows={7} className="mt-2 block w-full resize-y border border-border bg-secondary px-3 py-3 text-sm outline-none focus:border-accent" /></label><label className="flex items-center gap-3 border border-border bg-secondary p-3 text-sm"><input type="checkbox" checked={evidenceAttached} onChange={(event) => setEvidenceAttached(event.target.checked)} /> Evidence will be attached later through a protected channel.</label><button type="submit" className="inline-flex items-center gap-2 bg-foreground px-4 py-3 text-sm font-medium text-background"><Send className="h-4 w-4" />Submit for verification</button>{error && <p className="text-sm text-red-700">{error}</p>}{submitted && <p className="font-mono text-xs uppercase tracking-widest text-accent">Submitted: {submitted} / state SUBMITTED</p>}</form><div className="bg-secondary p-6 md:p-8 lg:col-span-5"><p className="font-mono text-xs uppercase tracking-widest text-muted-foreground">Privacy boundary</p><h2 className="mt-6 text-3xl font-semibold tracking-tight">Prove eligibility. Keep identity private.</h2><div className="mt-8 border-y border-border py-4"><p className="font-mono text-[10px] uppercase tracking-widest text-accent">Current status</p><p className="mt-2 text-sm font-semibold">MIDNIGHT INTEGRATION: NOT CONFIGURED</p><p className="mt-2 text-sm leading-relaxed text-muted-foreground">This development intake has no encryption, authentication, evidence storage, or durable persistence. Do not submit real sensitive material.</p></div></div></div>
}
